### ISSUE TITLE
2.0.1 breaks auto import

### ISSUE THREAD

**Issue by Foobartender** [quasarframework/vue-cli-plugin-quasar#30]
**Describe the bug**
Quasar components are not imported automatically.

**To Reproduce**
1. Create a new Vue CLI project
2. Add quasar.
3. Edit files to use TS classes.

**Expected behavior**
Should work.

**Platform (please complete the following information):**
OS: Arch Linux
Node: 14.1.0
NPM: 6.14.4
Browsers: Firefox

**Additional context**
I attached a sample project. It works with vue-cli-plugin-quasar 2.0.0 but not with 2.0.1.
[vqtest.tar.gz](https://github.com/quasarframework/vue-cli-plugin-quasar/files/4564795/vqtest.tar.gz)

**Comment by IlCallo** [comment]
Well, this is strange: v2.0.1 was exactly a fix to make Vue router components import to work when using Class API

https://github.com/quasarframework/quasar/issues/6803

Will check what's going on there

**Comment by IlCallo** [comment]
I checked with a member of Vue core team and apparently the problem relies on Vue instances [caching system](https://github.com/vuejs/vue/blob/dev/src/core/instance/init.js#L93): we keep the same `component.options.components` reference, so Vue doesn't notice something changed and doesn't update it accordingly.

If any `component.options` property is modified ([meaning its reference changes](https://github.com/vuejs/vue/blob/dev/src/core/instance/init.js#L122)), the update is automatically handled. So it's always needed to create a new object.
But because we also need original object prototype (to avoid breaking again https://github.com/quasarframework/quasar/issues/6803), we need to create a new object using `Object.create()`, and then assign everything to it (even enumerable properties of the old object, just in case someone relied on them).

Definitive (I hope) solution is to use this code:
```js
component.options.components = Object.assign(Object.create(component.options.components || null), component.options.components || {}, {${comp}})
```

Note that the problem was bound to `Vue.extend` usage (called internally by Vue Class Component). It wasn't limited to TS users, but JS users usually just return the object options, avoiding it.
